name: share_plus_platform_interface
publish_to: none
description: A common platform interface for the share_plus plugin.
version: 5.0.1
homepage: https://github.com/fluttercommunity/plus_plugins
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

dependencies:
  cross_file: ^0.3.4+1
  flutter:
    sdk: flutter
  meta: ^1.11.0
  mime: ">=1.0.4 <3.0.0"
  plugin_platform_interface: 
    git: https://github.com/kumsumit/plugin_platform_interface.git
  path_provider: 
    git: https://github.com/kumsumit/path_provider.git
  uuid: ">=4.3.3 <5.0.0"


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  flutter_lints: ^5.0.0
  test: ^1.24.9

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=3.19.3"
